### ISSUE TITLE
src/graphql/schemas.js field syntax does not work well with React/js front end

### ISSUE THREAD

**Issue by kyle-richardson** [Lambda-School-Labs/neighborhood-chef-be#37]
Running into issues specifically with Date since that is a prototype class, hence a reserved word in javascript, but to make it uniform, we may want to make them all lower case.

**Comment by PaulMEdwards** [comment]
I think this is resolved... Please confirm, @kyle-richardson. If so, go ahead and close it. Thx!

**Comment by kyle-richardson** [comment]
yup new camel case with starting lowercase resolved issue.  thanks
