### ISSUE TITLE
pg-docker.bash system compatibility problems

### ISSUE THREAD

**Issue by PaulMEdwards** [Lambda-School-Labs/neighborhood-chef-be#4]
Testing of pg-docker.bash script on @Aaroneld 's PC and @patrick-replogle 's Mac both exhibited trouble with the POSTGRES_DATA_PATH having a tilde (~) instead of the actual home directory.

**Comment by Aaroneld** [comment]
🐳 Land Ho! 🐋 I personally vetted the script myself
